"use client";
import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import {
  IconBug,
  IconGitBranch,
  IconGraph,
  IconBinary,
} from "@tabler/icons-react";
import SpotlightCard from "../reactbits/SpotlightCard";

const features = [
  {
    icon: IconBug,
    label: "STRESS TEST",
    title: "20+ adversarial attack categories",
    desc: "Prompt injection, tool abuse, hallucination, context poisoning, jailbreak, infinite loops — all generated by AI, targeted at your agent's actual capabilities.",
    detail: (
      <div
        className="mt-4 overflow-hidden"
        style={{
          borderRadius: 6,
          border: "1px solid rgba(255,255,255,0.06)",
          background: "rgba(0,0,0,0.3)",
          fontFamily: "var(--font-geist-mono, monospace)",
          fontSize: 12,
          padding: "12px 14px",
          color: "#666672",
        }}
      >
        <div>
          <span style={{ color: "#00C896" }}>categories:</span> prompt_injection, tool_abuse,
        </div>
        <div>
          {"  "}hallucination, context_poison,
        </div>
        <div>
          {"  "}jailbreak, infinite_loop, data_exfil,
        </div>
        <div>
          {"  "}role_confusion, encoding_attacks...
        </div>
        <div className="mt-2">
          <span style={{ color: "#F59E0B" }}>depth:</span> 5
        </div>
        <div>
          <span style={{ color: "#F59E0B" }}>runs_per_category:</span> 10
        </div>
      </div>
    ),
  },
  {
    icon: IconGraph,
    label: "GRAPH REPLAY",
    title: "Every decision, visualized",
    desc: "Each simulation run produces a directed graph. Replay any run step-by-step. See which tool was called, what the model reasoned, and where it went wrong.",
    detail: (
      <div
        className="mt-4 flex items-center justify-center"
        style={{ height: 80 }}
      >
        {/* Mini graph visualization */}
        <svg width="200" height="60" viewBox="0 0 200 60">
          {/* edges */}
          <line x1="30" y1="30" x2="80" y2="15" stroke="#333338" strokeWidth="1" />
          <line x1="30" y1="30" x2="80" y2="45" stroke="#333338" strokeWidth="1" />
          <line x1="80" y1="15" x2="140" y2="15" stroke="#00C896" strokeWidth="1" />
          <line x1="80" y1="45" x2="140" y2="45" stroke="#FF4444" strokeWidth="1" />
          <line x1="140" y1="15" x2="180" y2="30" stroke="#00C896" strokeWidth="1" />
          {/* nodes */}
          <circle cx="30" cy="30" r="6" fill="#7B61FF" />
          <circle cx="80" cy="15" r="5" fill="#00C896" />
          <circle cx="80" cy="45" r="5" fill="#FF4444" />
          <circle cx="140" cy="15" r="5" fill="#00C896" />
          <circle cx="140" cy="45" r="5" fill="#FF4444" />
          <circle cx="180" cy="30" r="5" fill="#00C896" />
          {/* Labels */}
          <text x="28" y="50" fill="#444450" fontSize="8" textAnchor="middle">start</text>
          <text x="140" y="8" fill="#00C896" fontSize="8" textAnchor="middle">pass</text>
          <text x="140" y="57" fill="#FF4444" fontSize="8" textAnchor="middle">fail</text>
        </svg>
      </div>
    ),
  },
  {
    icon: IconGitBranch,
    label: "FORK & REPLAY",
    title: "Fork from any failure node",
    desc: "Find a failure? Fork the graph from that exact node, tweak your prompt, and replay — without re-running the entire simulation.",
    detail: (
      <div
        className="mt-4"
        style={{
          borderRadius: 6,
          border: "1px solid rgba(123,97,255,0.2)",
          background: "rgba(123,97,255,0.05)",
          fontFamily: "var(--font-geist-mono, monospace)",
          fontSize: 12,
          padding: "12px 14px",
        }}
      >
        <div style={{ color: "#7B61FF" }}>
          <span style={{ color: "#666672" }}>$</span> watchllm fork --run abc123 --from node-7
        </div>
        <div className="mt-1" style={{ color: "#444450" }}>
          → forking from tool_call: search_documents
        </div>
        <div style={{ color: "#444450" }}>
          → replaying with updated system prompt...
        </div>
        <div className="mt-1" style={{ color: "#00C896" }}>
          ✓ forked run: def456 — all assertions pass
        </div>
      </div>
    ),
  },
  {
    icon: IconBinary,
    label: "BEHAVIORAL VERSIONING",
    title: "Git for agent behavior",
    desc: "Every simulation is automatically versioned. Graph diffs show you exactly which user flows changed — not just which model version you're running.",
    detail: (
      <div
        className="mt-4"
        style={{
          borderRadius: 6,
          border: "1px solid rgba(255,255,255,0.06)",
          background: "rgba(0,0,0,0.3)",
          fontFamily: "var(--font-geist-mono, monospace)",
          fontSize: 12,
          padding: "12px 14px",
        }}
      >
        <div style={{ color: "#666672" }}>behavioral diff: v2.1 → v2.2</div>
        <div className="mt-2" style={{ color: "#FF4444" }}>
          - tool_search → hallucinated 23% of responses
        </div>
        <div style={{ color: "#00C896" }}>
          + tool_search → accurate on 98% (new retrieval)
        </div>
        <div className="mt-1" style={{ color: "#FF4444" }}>
          - prompt_injection → bypassed guardrail
        </div>
        <div style={{ color: "#00C896" }}>
          + prompt_injection → blocked (input filter v3)
        </div>
      </div>
    ),
  },
];

export default function Features() {
  const ref = useRef<HTMLElement>(null);
  const inView = useInView(ref, { once: true, amount: 0.15 });

  return (
    <section
      ref={ref}
      className="flex flex-col items-center px-6"
      style={{ paddingTop: 100, paddingBottom: 100, background: "#060608" }}
    >
      <motion.span
        initial={{ opacity: 0 }}
        animate={inView ? { opacity: 1 } : {}}
        transition={{ duration: 0.4 }}
        style={{
          fontSize: 13,
          color: "#00C896",
          fontWeight: 500,
          letterSpacing: "0.05em",
          fontFamily: "var(--font-geist-mono, monospace)",
        }}
      >
        CORE FEATURES
      </motion.span>
      <motion.h2
        initial={{ opacity: 0, y: 20 }}
        animate={inView ? { opacity: 1, y: 0 } : {}}
        transition={{ duration: 0.5, delay: 0.1, ease: "easeOut" }}
        className="text-center mt-4"
        style={{
          fontSize: "clamp(28px, 3vw, 40px)",
          fontWeight: 600,
          color: "#EDEDED",
          lineHeight: 1.15,
          letterSpacing: "-0.02em",
        }}
      >
        Ship agents that don&apos;t break
      </motion.h2>

      <div
        className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-14 w-full"
        style={{ maxWidth: 780 }}
      >
        {features.map((f, i) => (
          <motion.div
            key={f.label}
            initial={{ opacity: 0, y: 20 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.4, delay: 0.2 + i * 0.1, ease: "easeOut" }}
          >
            <SpotlightCard
              className="h-full p-5"
              spotlightColor="rgba(0, 200, 150, 0.10)"
              style={{
                borderRadius: 10,
                border: "1px solid rgba(255,255,255,0.06)",
                background: "rgba(10,10,14,0.6)",
              }}
            >
              <div className="flex items-center gap-2 mb-3">
                <f.icon size={16} style={{ color: "#00C896" }} />
                <span
                  style={{
                    fontSize: 11,
                    color: "#00C896",
                    fontWeight: 600,
                    letterSpacing: "0.08em",
                    fontFamily: "var(--font-geist-mono, monospace)",
                  }}
                >
                  {f.label}
                </span>
              </div>
              <h3
                style={{
                  fontSize: 18,
                  fontWeight: 600,
                  color: "#EDEDED",
                  lineHeight: 1.3,
                }}
              >
                {f.title}
              </h3>
              <p
                style={{
                  fontSize: 14,
                  color: "#666672",
                  marginTop: 8,
                  lineHeight: 1.6,
                }}
              >
                {f.desc}
              </p>
              {f.detail}
            </SpotlightCard>
          </motion.div>
        ))}
      </div>
    </section>
  );
}
